components/product/currentprice.htm, components/product/price.htm, components/products/item.htm
This fixes the escaping of the already by twig converted chars.
Not sure if it is safe to allow raw markup there, but I cannot see any potential dangerous scenarios...
=> Fix #125 (doubled escaping)

components/product/cart.htm
Only show the properties html-tag if the right inventory management method is selected.
=> Show properties html-tag only on variant method

components/AddressForm.php
When clicking on Form Addresses component, it throws the following error:
"substr() expects parameter 1 to be string, array given" on line 469 of /Users/marcomessa/dev/satemac/vendor/laravel/framework/src/Illuminate/Support/Str.php"
I edited AddressForm::getAddressOptions() to make it return an array.
=> Fix getAddressOptions return type

classes/index/mysql/MySQL.php
Thanks for this project ;) 
This PR fix a bug I have introduced in #387 sorry for that.
Cast to int is not supported on MySQL 5.7 (only supported by MariaDB)
https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast
=> MySQL cast sort_orders to unsigned

models/order/columns.yaml
This avoid the PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'order_state' in 'order clause' when trying to sort  it
=> order_state column of Order model can't be sortable

models/GeneralSettings.php, models/settings/fields_general.yaml
The `GeneralSettings` model has 6 dropdowns that need to be pointed at the correct page with a specified component. The old approach loads all pages listed in the CMS, now only the pages are displayed that have the actual component present.
=> only load pages that have the asked component in GeneralSettings

classes/feeds/GoogleMerchantFeed.php
This fixes incorrect URLs for variants in the Google Merchant Feed.
=> Use hashed ID for variant URLs

models/PaymentLog.php, models/paymentlog/columns.yaml
Instead of order_id, order_number is now displayed in the list of payment logs. This solves the problem of mismatch of order numbers in the list of orders and payment logs if the id and order_number are different in the Order model (for some reason, I had an out of sync id and order_id.).
=> Updating PaymentLog model

models/Discount.php, models/ShippingMethod.php
Double quotes is used for escaping identifiers, single quotes is for strings.
Fixes #498
=> Fix bad SQL in morph conditions

classes/traits/ProductPriceTable.php, controllers/Products.php
I've been working on a project that requires to add some info to the product price table. With these changes, one could extend the config by overriding the `offline/mall/controllers/products/config_table.yaml` file in this way:
in `MyVendor\MyPlugin\Plugin.php`:
``` php
public function boot()
{
\OFFLINE\Mall\Controllers\Products::extend(function ($controller) {
$controller->productPriceTableConfig = '$/myvendor/myplugin/controllers/products/config_table.yaml';
});
}
```
And in `myvendor/myplugin/controllers/products/config_table.yaml` one could do something like:
```yaml
dataSource: client
keyFrom: id
recordsPerPage: false
adding: false
deleting: false
searching: false
alias: pricetable
columns:
name:
title: offline.mall::lang.common.product_or_variant
readOnly: true
stock:
title: …
```
=> Extend product price table config

controllers/currencies/config_list.yaml, controllers/paymentmethods/config_list.yaml, controllers/pricecategories/config_list.yaml, controllers/propertygroups/config_list.yaml, controllers/shippingmethods/config_list.yaml, models/brand/columns.yaml, models/currency/columns.yaml, models/notification/columns.yaml, models/orderstate/columns.yaml, models/paymentmethod/columns.yaml, models/pricecategory/columns.yaml, models/propertygroup/columns.yaml, models/shippingmethod/columns.yaml
Every backend controller that lists models with `sort_order` attribute gets invisible column and `defaultSort`: #518
=> Sorting through sort orders

models/Order.php
I've a situation where i'd like to collect an extra field (delivery date), from the cart and assign it to the order upon creation. Since the order creation is within a transaction, and the cart gets deleted within the transaction, I can't find a way to transfer elements from one to the other.
Conceptually, I'm requesting an event to be fired within the transaction that passes both the recently created order and the soon to be deleted cart. This would allow adding any number of extra fields to a cart and manipulating the resulting order how the developer sees fit. 
In any Plugin.php, one would:
```php
Event::listen('mall.order.afterCreate', function($order, $cart){
$order->extraField = $cart->extraField;
// or
$order->existingAttribute = $cart->newManipulatingMethod();
});
```
You get the …
=> Event after order create and before cart delete

controllers/Products.php
added default value empty string in Request::header in \Request::header('X-OCTOBER-REQUEST-HANDLER','') because 
str_contains() accept strict type "string".
\Request::header('X-OCTOBER-REQUEST-HANDLER') return null, if header X-OCTOBER-REQUEST-HANDLER is empty.
When you have declare(strict_types=1); it cause to fatal error.
=>  add default value empty string in Request::header

controllers/orders/_detail_scoreboard.htm
Invalid link uncovered itself while adding Mall to OctoberCMS installation with existing RainLab.Users that weren't Mall.Customers, @tobias-kuendig
=> Fixed customer user backend link in order scoreboard

classes/registration/BootExtensions.php
Thinking about extensibility, lowering the priority on the `backend.form.extendFields` or `backend.menu.extendItems` events would allow a third party plugin to control the execution order of colliding extension features. I've actually have had to do it in a personal fork in order to properly customize the user preview on Rainlab/User.
=> Allows for event listen execution sorting

updates/version.yaml
Today I cannot fresh install oc-mall. After some struggle, I found that the colon in updates.yaml break installation process throwing this error:
In VersionManager.php line 565:
preg_match() expects parameter 2 to be string, array given 
Hope this help!
=> Removed colon

models/paymentmethod/fields.yaml, models/shippingmethod/fields.yaml
Adding svg to logo upload is handy and does not have security issues because it's used on <img src="">
=> enabled  svg and webp image formats to Payment and Shipping Methods

formwidgets/PropertyFields.php
Use the sort_order key when rendering the properties in the PropertyFields formwidget.
=> sort properties when rendering the mall.propertyfields formwidget

models/Variant.php
Currently "[OFFLINE.Mall] All Shop Variants" type menu items show published variants only, which is correct. But they also show published variants of products which have not been published. This is incorrect. This fix aims to correct this by also filtering on the published property of the product related to each variant.
=> Only show published variants in menus

classes/utils/DefaultMoney.php, classes/utils/Money.php
Currently the `|money` twig filter can be one number off on the last decimal when it's used on a total from the `TotalsCalculator`. This pull request fixes that. This occurs when one of the calculated totals has more decimals than the used currency and needs rounding.
How to reproduce the problem:
- Use a currency with 2 decimals
- Put a product with a price of 243.40 and 6% tax in the `TotalsCalculator`
- Output the `TotalsCalculator`'s `productPreTaxes()`, `productTaxes()`, `productPostTaxes()` via the `|money` twig filter
- The sum of `productPreTaxes()` and `productTaxes()` will be 0.01 off from `productPostTaxes()`
=> Fix money rounding

composer.json
The package has moved and installation of this plugin through composer leads to errors in our pipelines.
https://packagist.org/packages/filebase/filebase
=> Use moved filebase package

models/Variant.php
This fixes a small issue where the product variant id is an int instead of the hashed id, for example in generated sitemaps.
=> Small fix for variants in the resolveItem() method

formwidgets/Price.php
adding `$value` to Price widget.
With that, developers can set a default price for a new product.
```php
class Plugin {
public function boot() {
Product::extend(function (Product $model) {
$model->bindEvent('model.form.filterFields', function (\Backend\Widgets\Form $formWidget, $fields, $context) use ($model) {
if ($context !== 'create') {
return;
}
$formWidget->getFormWidget('_initial_price')->value = "5";
})
[..]
}
```
=> Changing default price when creating a new product.

components/ProductReviews.php
Otherwise `$q->where('customer_id', Auth::getUser()->customer->id);` would led to a null exception.
=> fix a bug, when user is logged in, but is not a customer

controllers/propertygroups/config_relation.yaml
If you have a lot of properties (1000+), this interface becomes unusable otherwise.
Like this, it is nicely searchable and paginated.
=> Add search and record limitation to properties

docs/getting-started/installation.md
The theme actually requires the SiteSearch plugin to be installed.
The other dependencies are already fullfilled by the Mall plugin itself.
=> Add additional dependency for demo theme

components/QuickCheckout.php
Currently, it throws this error (from the demo site):
`Type error: Argument 1 passed to OFFLINE\Mall\Models\Order::byCustomer() must be an instance of OFFLINE\Mall\Models\Customer, null given, called in /home/offlineg/public_html/_domains/mall.offline.swiss/plugins/offline/mall/components/QuickCheckout.php on line 413`
When the user is requesting the payment step with the order parameter and they are not logged in, redirect the user to the login page. Bypassing the byCustomer() completely.
=> Payment step: Redirect to login

components/PaymentMethodSelector.php
Catch ModelNotFoundException exception when an invalid orderId is passed.
Invalid orderId includes:
- Random order ID
- Order ID that does not belong to a user
Redirect to '/' to suppress the exception
=> Catch ModelNotFoundException exception

components/Products.php
This PR add a small condition to getFilters method of product component.
If category_id key is detected on the QueryString, we don't override it by defining categories using component properties. It allow to use filter system with categories.
=> Use QueryString "category_id" filter when present instead of category calculated based on component properties

updates/version.yaml
This is to address the following warning
> PHP Deprecated:  Using the unquoted scalar value "!!! This release does not contain any code updates..." is deprecated since Symfony 3.3 and will be considered as a tagged value in 4.0
It will be made obsolete soon and throw an exception
=> Remedy YAML syntax

components/cart/table/shipping.htm, components/quickcheckout/carttable/shipping.htm, lang/en/frontend.php
In the cart view, when no shipping method is selected, show a message instead of empty name and zero price.
=> Show message when shipping method is not selected

components/Cart.php
When removing an item from the cart that has been removed (either from the quick checkout page or cart page from another tab), the firstOrFail will throw a ModelNotFoundException. The proposed change will catch the ModelNotFoundException and return null instead. The onRemoveProduct function can then null-check the $product before removing the product.
=> Catch ModelNotFoundException

components/WishlistButton.php
By adding items to $this->page['items'] instead of renderPartial function, you allow theme developpers to create their own partials and set their own wrapper, which allow more possibilities in term of theming.
=> Attribute {{ items }} variable to page scope

components/QuickCheckout.php
The function was present with the cart component but missing from quickCheckout component. It's basically a copy of the method of the cart component with minor modifications for a better integration with quickCheckout component.
=> Add onRemoveDiscountCode method to quickCheckout component

composer.json
The plugin is not working out of the box because they require RainLab plugins in `Plugin.php` but are not required in the `composer.json` file. This PR should fix it and add the plugins upon installation of the Mall plugin when not installed already.
=> Added RainLab plugins in composer requirements

components/Product.php
This change is intended to hide variants that are not published.
Showing unpublished variants results in so many 404 errors on the site.
=> Hide unpublished product's variants

controllers/products/_list_toolbar.htm
This proposal adds an event hook to the products controller's toolbar so that it can be easily heard from a third party plugin.
Example of use of the feature
```php
/**
* Extend products view toolbar
*/
Event::listen('offline.mall.extendProductsToolbar', function ($controller) {
// return html button code
});
```
=> Add event hook to product's toolbar

classes/events/MailingEventHandler.php
Add link to user account page in mail sent when order state change.
Fix #880
=> Bugfix mail's link on order state change

components/Cart.php
After product removing cart model’s object has postponed relations (removed product observed within)
So new_items_count counts removed product
In the setData method there is updated CartModel selecting, which has stable relations, so using $this->cart helps to count new cart’s products count
Tested in the October 1.1
=> Bug in the Cart Component with removing product: new_items_count counts removed product

lang/fr/lang.php
Translate `gtin` and `mpn`  keys according to Google Merchant Center Help.  
source: 
- https://support.google.com/merchants/answer/6324482?hl=fr
- https://support.google.com/merchants/answer/6324461?hl=fr
=> Update French lang

docs/development/events.md, models/ShippingMethod.php
This event extend the shipping methods filtering process to allow third-party plugins to filter themselves the available shipping methods.
The above example show how to reject a shipping method by his ID if the cart contains a product in a specific category.
````php
Event::listen('mall.shipping.methods.availability', function (&$availableShippingMethods, $cart, $whishlist) {
// Check if cart contains products in a specific category
$inCategory = $cart->products->contains(function ($product) {
return $product->product->categories->where('code', 'my-category-code')->count() > 0;
});
// Reject some shipping methods
$availableShippingMethods = $availableShippingMethods->reject(function ($item) use ($inCategory) {
return ($item->id == 2 && $inCategory);
});
});
````
=> Add event to shipping methods availability

composer.json
This fixes the dependency only, haven't been able to test the barryvdh/laravel-dompdf:1.0 package without it. Potential fix for:
```
Your requirements could not be resolved to an installable set of packages.
Problem 1
- illuminate/support[v5.6.0, ..., 5.8.x-dev] require php ^7.1.3 -> your php version (8.0.3) does not satisfy that requirement.
- illuminate/support[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.0.3) does not satisfy that requirement.
- illuminate/support[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.0.3) does not satisfy that requirement.
- illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.0.3) does not satisfy that requirement.
- Root composer.json requires offline/oc-mall-plugin ^1.16 -> satisfiable by …
```
=> October v3 / Laravel 9 package support

classes/customer/DefaultSignUpHandler.php
On createUser() , prevent from erasing $data array to let the possibility for other modules to extend user model.
=> Allow other modules to extend user model. 

models/PropertyGroup.php, models/ShippingMethod.php
Laravel 7+ introduced changes to getOriginal() which cause infinite loop when called from within an accessor.
(see https://laravel.com/docs/7.x/upgrade#factory-types)
Laravel now uses method return signatures which must be honored when overriding methods. This PR also fixes the ShippingMethod::jsonSerialize() signature.
=> Fix issues with newer Laravel versions.

models/address/columns.yaml
I see that event in the demo site, the `customer` column when viewing addresses is always empty.  
This modification add the correct information to the column.  
The column was rename to suit October's documentation : 
> Be careful not to name relations the same as existing database columns. For example, using a name group_id could break the group relation due to a naming conflict.  
see : [Backend / Lists / Relation](https://docs.octobercms.com/2.x/backend/lists.html#relation)
=> Update Address columns definition

classes/index/ProductEntry.php, models/Product.php
When updating a Product, I get the following error:
```
"SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2022-06-01T03:48:31.000000Z' for column `natasha_aerocom`.`offline_mall_index`.`created_at` at row 1 (SQL: update `offline_mall_index` set `created_at` = 2022-06-01T03:48:31.000000Z where `id` = 1)" on line 742 of /var/www/vhosts/aerocom.studioazura.com/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php
```
This PR addresses the issue.
It's also possible to convert `created_at` value in `classes/index/mysql/MySQL.php` ... not sure which one is best.
=> Fix created_at format error when updating index table

components/Product.php, components/quickcheckout/scripts.htm
If redirectOnPropertyChange is false, not all properties are listed which doesnt make sense at all.
=> Various improvements

models/Product.php
Allow the PDFMaker to be used in the context of a product, in order to allow for back-end uses like a product information sheet, or a list of purchases of a specific product.
=> Add PDFMaker trait to Product model

components/Wishlists.php
This PR is aimed to allow Wishlist page to load a specific wish list item by passing his hashed Id as parameter.   
**The `id` parameter must be set with an hash id** : `https://mall.offline.swiss/en/wishlists/r8dolq6Z`.
```twig
title = "Wishlists"
url = "/wishlists/:id?"
layout = "default"
is_hidden = 0
[viewBag]
localeUrl[de] = "/wunschlisten/:id?"
[wishlists]
showShipping = 1
==
{% component 'wishlists' %}
```
If no id parameter is passed, the defaut behavior is used and the first item of the list get loaded.  
This can be useful if you dynamically build a wishlist from the items in the store (example project configurator) and you want to  redirect the visitor to this newly created list.
=> Allow wishlist load by page parameter

classes/events/MailingEventHandler.php
this is a more complete fix regarding #952 as it has all the event handlers updated. [October v3]
=> Fixes missing method MailingEventHandler::__invoke() additional handlers

models/Currency.php
Don't include date in attributes casting
Back-port commit #969  in v2 branch.
=> Avoid Currency dates to be cast as ISO dates

classes/payments/PaymentProvider.php
Hi guys, overridden and default `PaymentProvider` templates use different `Twig` instances. The overridden one cannot resolve some Twig tags like `put`. Should we use the same Twig instance for both? This should fix the #997.
=> Uses same Twig instance for overridden and default templates

controllers/Categories.php
Ciao!
This PR adds the `listAfterReorder()` method to `OFFLINE\Mall\Controllers\Categories` in order to clear the cache after a reorder happens.
In the `Controllers\Categories` Mall uses the old `ReorderController` and the related `onReorder()` method to clear the categories' cache if a reorder happens. 
In OctoberCMS v3 the `ReorderController` is deprecated and we should use the `ListController` instead. The `Controller\Categories` uses the new `ListController` already, but it doesn't clear the cache after a reorder. This ends up in a 404 error if the category URL has changed. E.g. `/category/bikes/mountainbikes` to `/category/mountainbikes`.
=> Clears categories cache after reorder

updates/add_product_variants_sort_order.php
Was getting this error without the namespace:
```
Migrating Mall (OFFLINE.Mall) plugin...
INFO  Running migrations.
2.0.23:   Make Product variants sortable (thanks to @mjauvin) .............................................................. 1ms FAIL
In add_product_variants_sort_order.php line 5:
The use statement with non-compound name 'Schema' has no effect  
```
=> Add missing namespace to migration.

classes/observers/ProductObserver.php, classes/observers/VariantObserver.php, models/Product.php
The `softDelete` relation property will make sure the related records are properly deleted/restored when deleting the parent record.
ref. Database/Traits/SoftDelete.php trait
=> Use softDelete property for variants relation

classes/registration/BootServiceContainer.php, classes/traits/PDFMaker.php, composer.json, config/pdf.php
While trying out Laravel 10 I found out that we need [`barryvdh/laravel-dompdf:2.0.1`](https://github.com/barryvdh/laravel-dompdf/releases/tag/v2.0.1)
This PR sets `barryvdh/laravel-dompdf` to `^2.0` and updates [deprecations](https://github.com/barryvdh/laravel-dompdf/releases/tag/v2.0.0).
=> Support DomPDF 2.x / Support Laravel 10

classes/index/ProductEntry.php, classes/index/VariantEntry.php, components/ProductsFilter.php
This pull request addresses an issue where '0' values were being inadvertently filtered out in the array_filter function. By adding the strlen callback to the array_filter call, '0' values are now retained in the resulting array. This change ensures consistent behavior and prevents unintentional data loss when dealing with propertyvalues containing '0' values.
=> Ensure '0' values are not filtered out in array_filter function

classes/traits/PriceAccessors.php, classes/traits/category/Slug.php, models/Category.php
Solved 2x "Deprecated: Optional parameter declared before required parameter"
Solved 1x "Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in"
=> Solved several deprecated messages with PHP 8.*

classes/customer/DefaultSignUpHandler.php, docs/development/events.md
This PR allow developers to extend the validation messages when a customer signup.  
It is currently possible to add/extend validator rules, but not the associated messages.
This can be added to V3 branch without creating any breaking changes.
=> Allow extendind Signup messages

classes/jobs/UpdateUniquePropertyForCategory.php, classes/queries/UniquePropertyValuesInCategoriesQuery.php, classes/registration/BootEvents.php, models/Category.php, models/Product.php, models/Property.php, models/PropertyGroup.php, models/PropertyValue.php, models/UniquePropertyValue.php, phpunit.xml, tests/queries/UniquePropertyValuesInCategoriesQueryTest.php, updates/031_01-create_unique_property_values_table.php, updates/version.yaml
Hi @tobias-kuendig,
In regards to https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/1149 I'm filling this PR. It basically moves the "big" query to queue when updating particular models, but makes fetching really quick. In my case it optimised loading the page from ~3 minutes to 8 seconds with the same functionality (I know it's still long, but let's ignore it for now ;) ).
I wrote a test that checks if the new approach returns the same set of values. Underneath, I haven't changed the original query, I use it to fill correct records to the db.
It's a first version so I'm open to any suggestions.
Cheers,
Tomasz Strojny
=> Optimise unique property values query

models/UniquePropertyValue.php, updates/version.yaml
Hi @tobias-kuendig,
As mentioned, one more thing re unique properties.
It turned out that we were adding too many queue jobs. The fix is just preventing it by running single command.
Not a big deal.
Thanks for a great plugin mate!
=> Prevent from adding too many queue jobs for UniquePropertyValue

updates/seeders/tables/CustomerTableSeeder.php
Hi!
using the newest github and october registry version of the mall plugin while seeding with example data using:
```bash
php artisan mall:seed --verbose -d 
```
i encountered an:
```bash
The surname field is required.
/home/prfl/Projects/depcore/oc-instance/vendor/october/rain/src/Database/Traits/Validation.php
```
the fix was to edit the CustomerTableSeeder.php where the parameters were deprecated.
changing first_name to name and last_name to surname fixed the error!
Have a great day and keep up with the great work of bringing ecommerce to october <3
=> fixed "The surname field is required" Validation bug

classes/index/mysql/MySQL.php, updates/version.yaml
Hi @tobias-kuendig !
The PR is basically self explanatory but yea, Laravel 10 changed the way expressions are converted to strings. See the docs here: https://laravel.com/docs/10.x/upgrade#database-expressions
Here's the commit in Laravel's code (yea I looked for a better way ;) ): 
https://github.com/illuminate/database/commit/34a71007a8f3a5f617c4e608d73ec3a1aced9272#diff-8466082f196fa1a3b3ad9815d14d79e5139ae900d2edf7c74ea922a67b281a45R34
To keep backwards compatibility I decided to check Laravel's version and apply the fix only for the versions above 10. Not sure it's the best way to go so let me know if you'd see it solved better.
Thanks,
Tomasz
=> MySQL raw expressions have __toString removed for Laravel 10+

components/ProductsFilter.php
When using the `[productsFilter]` component with the `includeChildren` set to false, this error occurs:
```
OFFLINE\Mall\Models\UniquePropertyValue::hydratePropertyValuesForCategories(): Argument #1 ($categories) must be of type Illuminate\Database\Eloquent\Collection, October\Rain\Support\Collection given, called in /app/plugins/offline/mall/models/Property.php on line 132
```
This PR addresses that by creating a new Eloquent Collection instead of using the `collect()` function which creates a `October\Rain\Support\Collection`
=> Fix products filter category collection type

components/productsfilter/scripts.htm
I noticed when filtering, the path was lost. So when I'm on a page with the url `/assortiment/clothing` and filter, the url gets updated to `/?0=on&sort=bestseller`. 
This change fixes that by preserving the current path name
=> fix: preserve current path on filter

components/Cart.php
The docs [show an example](https://offline-gmbh.github.io/oc-mall-plugin/guide/components/cart.html#example-implementations) of having a cart counter. At the moment, it's not possible to update the total quantity when changing the amount in the cart, because this data is not returned by the ajax handler.
This PR fixes that by returning the same data as `onUpdateQuantity` does in the cart component.
The event listener to update the cart quantity would then look like this:
```js
$(function () {
var $count = $('.js-count');
$.subscribe('mall.cart.update', function (e, data) {
// You have access to different values here.
// console.log(data.item); // All item data
// console.log(data.quantity); // Added quantity
// console.log(data.new_items_count); // New total items in cart
// …
```
=> Return quantities onUpdateQuantity

classes/customer/DefaultSignUpHandler.php
I wanted to create a custom signup handler to add some rules like this:
```php
class SignUpHandlerWithPhoneNumber extends DefaultSignUpHandler {
public static function rules($forSignup = true): array
{
$rules = parent::rules($forSignup);
$rules['phone_number'] = ['required', 'string', 'max:32'];
return $rules;
}
protected function createUser($data, $requiresConfirmation)
{
$user = parent::createUser($data, $requiresConfirmation);
$user->phone_number = $data['phone_number'];
$user->save();
return $user;
}
}
```
However, since the `DefaultSignUpHandler` is calling the `rules` method using `self` it's calling the original method. Calling the method with `static` fixes that and allows me to extend the `DefaultSignUpHandler` and only override the rules method.
=> Use static instead of self in the default sign up handler

components/ProductsFilter.php
This Pull Request adds a filter to the `setBrands()` method in the `ProductFilter` component to ensure that only **brands associated with published products** are fetched. This prevents brands linked to unpublished products from being displayed, which is more in line with typical frontend visibility requirements.
- Added a `where('offline_mall_products.published', true)` condition in the `setBrands()` function to filter only **published products**.
- Updated the SQL query within `setBrands()` to only consider products that are published when determining which brands are associated with a given category.
Currently, the `setBrands()` method pulls in all brands present in the selected categories, including brands linked to unpublished products. This leads to inconsistent results and possible …
=> Filter Brands by only Published Products in ProductFilter Component

controllers/Orders.php
Updated the initRelation method by removing the hardcoded 'payment_logs' relation and modifying it to $this->initRelation($order).
This change allows greater flexibility when extending the model, enabling the use of different relations as needed. It ensures a more adaptable and extensible codebase while maintaining compatibility with the existing logic.
=> Refactor initRelation to Support Flexible Model Extensions

classes/registration/BootExtensions.php
I tried to hide the `customer_groups` side menu item:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/d4da4579011b1ff5591a739b1b9edd88a152f74c/classes/registration/BootExtensions.php#L124-L142
But I noticed that the subscribe priority does not work as described here: https://docs.octobercms.com/3.x/extend/services/event.html#subscribe-using-priority
So the listener below will still execute before the `customer_groups` is added.
```
Event::listen('backend.menu.extendItems', function (NavigationManager $manager) {
$manager->removeSideMenuItem('RainLab.User', 'user', 'customer_groups');
}, 4);
```
Illuminate's Event does not implement any priority, so using October's Event fixes this issue.
=> Use Event that supports priority

config/features.php
Introduced a new `log_failed_payments` boolean flag in `config/features.php`.
This flag controls whether failed payment attempts in the PaymentResult class should be logged. Default is `true` to preserve existing behavior.
=> Add config flag to enable or disable failed payment logging

models/Property.php
When (programmatically) adding an empty (null) option to a Property, an error can occur:
While it won't happen for users that just use the UI, this fix may help developers that add products from external systems.
=> Filter options

models/Variant.php
Prevents a new Variant from inheriting an existing Product id on create
Example of issue: `(new OFFLINE\Mall\Models\Variant(['product_id' => 1337]))->id` outputs `1337` if this is an existing product id
=> Prevent inheriting product id on create

updates/005_01-use_text_columns_for_variant_names.php, updates/006_01-use_text_columns_for_payment_log.php, updates/007_01-update_jsonable_columns_to_mediumtext.php, updates/021_01-update_description_short_column_of_products_table.php, updates/021_02-update_description_short_column_of_product_variants_table.php
Was having some problems with the plugin updates in a clean OctoberCMS v4 installation. These changes make the updates compatible with https://laravel.com/docs/11.x/upgrade#modifying-columns
=> Make updates compatible with Laravel 11 changes
