- controllers/Orders.php
- controllers/orders/_invoice_number_modal.htm
- controllers/orders/_toolbar.htm
- controllers/orders/show.htm
- lang/de/lang.php
- lang/en/lang.php
This addresses #22 
Not sure if the language strings are in a sensible location...
> Allow orders to be deleted

- models/Variant.php
There may be articles/good that have no stock value
> Make stock nullable

- models/Variant.php
Comes in handy when creating variants programmatically
> Add $fillable to Variant

- Plugin.php
- lang/de/lang.php
- lang/en/lang.php
- models/Category.php
This adds the ability to also display single category links in a menu. It is heavily copied from the blog plugin, but does not support nested (child) cateogories. It will only display the one selected category.
> Add single category list type

- controllers/categories/config_list.yaml
- controllers/discounts/config_list.yaml
- controllers/orders/config_list.yaml
- controllers/products/config_list.yaml
With this, all list in the backend will have the same pagination of 20 elements per page.
> Add pagination to lists where it was missing

- models/Variant.php
- models/variant/columns.yaml
- models/variant/fields.yaml
- updates/create_offline_mall_product_variants.php
> Add user_defined_id to variants

- Plugin.php
- models/Category.php
> Cache for menu

- models/Variant.php
Fixes #50 
The logic slightly changed, but it should be ok.
Tested and looked nice with:
- no properties in product, all in variant
- no properties in variant, all in product
- some properties in variant, some in product,
- Same as above but with prices, in both back and front end
- In backend via both variant edition and stock/price table edition
I had to tweak a little bit the `Product` component because it could not find the active variant and was displaying the product price instead.
I noticed a problem when mixing currencies like the following but it's either not because of this fix or because of my tweaks in the component (just reverted the model and same happened):
```
Product:
{ CHF: 100, EUR: 90 }
Variant:
{ CHF: 110, EUR: null }
```
In this case asking for the formatted price of …
> Merge parent product properties in variant

- composer.json
> Downgrade of nahid/jsonq to 5.2.0

- controllers/products/config_relation.yaml
On the other hand, Delete is very dangerous in this place.
> Remove is very needed here.

- components/cart/table/entry.htm
...and the variant was conceived, from the rib of main product.
> and said... "Let there be the variant!"

- classes/search/ProductsSearchProvider.php
- classes/traits/TranslatableRelation.php
- components/product/currentprice.htm
- components/product/price.htm
- components/products/item.htm
- models/Variant.php
This assumes that Variant names are translatable, however this does not work at the moment (see issue #128 )
> Multi language search

- controllers/Orders.php
- controllers/orders/_items.htm
- controllers/orders/show.htm
For OctoberCMS installations with customized `cms.backendUri`
> Fixed backend links in show Orders controller action

- controllers/orders/_tracking_modal.htm
> Fixed unreachable shipping state update checkbox

- controllers/Orders.php
- controllers/orders/_address.htm
- controllers/orders/_detail_scoreboard.htm
> Added customer and address links to show order backend page

- models/product/fields_edit.yaml
Fixes #367. Requires build 460
> Disable reviews field based on permissions

- classes/totals/ShippingTotal.php
- classes/totals/TotalsCalculator.php
- classes/traits/cart/Discounts.php
- lang/en/lang.php
- models/Discount.php
- models/discount/columns.yaml
- models/discount/fields.yaml
- updates/add_valid_from_column_to_discounts_table.php
- updates/version.yaml
This will add a valid from date for discounts, which will allow users to create discounts that will be available in the future.
> Add valid from date for discounts

- classes/index/mysql/MySQL.php
Same kind of issue that https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/374
> Fix manual order for MySQL

- classes/queries/UniquePropertyValuesInCategoriesQuery.php
- classes/traits/PropertyValues.php
- components/Product.php
- components/ProductReviews.php
- components/Products.php
- components/ProductsFilter.php
- components/product/properties/color.htm
- components/product/properties/default.htm
- components/productreviews/form.htm
- composer.json
- composer.lock
- controllers/Products.php
- controllers/products/config_relation.yaml
- docs/.vuepress/config.js
- docs/changelog/1.9.0.md
- formwidgets/PropertyFields.php
- formwidgets/propertyfields/partials/_colorpicker.htm
- formwidgets/propertyfields/partials/_propertyfields.htm
- formwidgets/propertyfields/partials/_textarea.htm
- formwidgets/propertyfields/partials/_textfield.htm
- models/Product.php
- models/Property.php
- models/PropertyValue.php
- models/Variant.php
> Translatable property values

- models/Product.php
Add `additional_descriptions`, and `additional_properties` to $fillable property for Product model.
> Add fillables

- models/Order.php
- models/order/_customer.htm
- models/order/columns.yaml
This fix https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/466
Now you can search for an order by customer name and email.
> Backend search order fix

- models/Service.php
Error thrown when trying to delete a service from the backend admin. Service gets softdeleted but not removed from the db.
> Fixes service deletion problem

- classes/stats/OrdersStats.php
I was playing with some test orders and came into this. Simple fix
> Total order number includes deleted elements

- formwidgets/PropertyFields.php
- lang/en/lang.php
- lang/fr/lang.php
- models/Property.php
Add new custom field type "switch"
> New "switch" custom field type

- formwidgets/PropertyFields.php
- formwidgets/propertyfields/partials/_datepicker.htm
- formwidgets/propertyfields/partials/_datetimepicker.htm
- lang/en/lang.php
- models/Property.php
> date & datetime properties

- classes/registration/BootExtensions.php
> fixes rainlab.user menu & permissions

- classes/registration/BootExtensions.php
otherwise, other plugin calling the isClassExtendedWith() will not get the proper result.
> use extendClassWith() method for extensibility

- formwidgets/PropertyFields.php
- models/Property.php
commit c5debeac98e88015259882d1ec02d47ce637b11b undid part of what commit f06d8a89acd785993021136f33fb4d0316b730c3 did.
this restores what has been removed.
> fix switch formfield type

- lang/nl/mail.php
Dutch translation of the email messages sent by the Mall Plugin
> Create mail.php (Dutch translation)

- models/Price.php
> Fix missing category relation key

- components/wishlists/contents.htm
Avoids getting an error message if the jQuery script is not yet loaded.
> Puts whishlists script in OctoberCms {% scripts %} tag

- components/Cart.php
> Fix showTaxes property title

- classes/payments/stripe/form.htm
Fixes #674
Fixes #677
- move submit variable assignment within if block
- add missing "$" symbol to variable identifier
> fix javascript error

- models/Address.php
Add customer_id to the $fillable array
Reference to the #695 issue
> Make customer_id $fillable for the Address model

- classes/traits/category/Slug.php
$model->id is a string here, not sure why that is. need to cast into integer.
> Fix category slug validation.

- classes/traits/cart/Discounts.php
- components/Cart.php
- components/DiscountApplier.php
- lang/en/lang.php
PR for [issue #726](https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/726)
> Limit amount of discount codes that can be applied

- classes/traits/cart/CartActions.php
Fix [issue #713](https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/713)
> Fix issue #713

- controllers/CategoriesProducts.php
More info in issue — https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/765
> Fix bug sort-order products on root category.

- classes/categoryfilter/sortorder/SortOrder.php
Allow extending the sorting options of the current category
> Allow custom sorting in SortOrder.php

- components/Product.php
> Allow first variant to be unpublished

- controllers/Products.php
On create new variant the price is not getting saved.
> Fixes save price on create variant

- classes/traits/ProductPriceTable.php
Its now workings. Variables of widgets wasn't not loaded. 
#788
> Fix issue Undefined index: pricetable #788

- components/Product.php
By providing this object to the page scope, you bring many new variables to the themers to be able to display nice confirmation popup or sidebar when you add a product to the cart.
> Associate the object returned by the addToCart method to $this->page['added']

- components/Product.php
Add price to page scope on stockCheckResponse() method
> Add price to page scope on stockCheckResponse() method

- controllers/products/_list_toolbar.htm
Move event hook from button to toolbar
> Bugfix for products toolbar event hook

- lang/cs/frontend.php
- lang/de/frontend.php
- lang/en/frontend.php
- lang/es/frontend.php
- lang/fa/frontend.php
- lang/fr/frontend.php
- lang/hu/frontend.php
- lang/it/frontend.php
- lang/nl/frontend.php
- lang/pt-br/frontend.php
- lang/ro/frontend.php
- lang/ru/frontend.php
-fix #838
Add `frontend.wishlist.deleted` translations in different languages.
> Add `frontend.wishlist.deleted` translations

- assets/pricewidget.css
- classes/index/mysql/MySQL.php
- classes/registration/BootEvents.php
- controllers/Categories.php
- controllers/PropertyGroups.php
- controllers/Services.php
- controllers/categories/_list_toolbar.htm
- controllers/categories/config_list.yaml
- controllers/customfields/_option_form.htm
- controllers/orders/_invoice_number_modal.htm
- controllers/orders/_tracking_modal.htm
- controllers/products/_price_table_modal.htm
- formwidgets/PropertyFields.php
- formwidgets/propertyfields/partials/_propertyfields.htm
- models/Address.php
- models/Notification.php
- models/Product.php
- models/PropertyGroup.php
- models/customfield/fields.yaml
Hi Tobias,
Just did some superficial testing, there are only a couple of things needed to make this compatible with v3.  As you correctly stated, this plugin stays within the framework's structure and this pays dividends when it comes to upgrading. Everything just works™
Changes are minimal refactor, just to get it running. Some of the patterns here can be repeated across other areas. Notes are in the commit messages.
Cheers
> Fixes compatibility with October CMS v3

- components/AddressList.php
- components/addresslist/list.htm
Display flash messages on address change/delete.
> AddressForm component fixes

- classes/events/MailingEventHandler.php
- classes/jobs/SendVirtualProductFiles.php
- classes/payments/PaymentRedirector.php
- classes/traits/category/MenuItems.php
- components/MyAccount.php
In the continuity of what @mjauvin has done in https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/955.
> Re-use CMS controller

- classes/traits/category/Translation.php
- composer.json
- controllers/Products.php
- models/Product.php
- models/Variant.php
This fix has **breaking changes** when used with translate plugin prior to v2.0.
> fixes for translate plugin v2.0

- models/Currency.php
Fix #954
See ref: https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/965#issuecomment-1299647770
> Avoid Currency dates to be cast as ISO dates

- classes/index/mysql/MySQL.php
Allow the offline_mall_index table to be extended via a third party plugin.
> Allow the extending of the index table

- updates/add_deleted_at_column_to_payments_log_table.php
Support soft deletion in payments log
> Add deleted_at column to offline_mall_payments_log table

- classes/index/mysql/MySQL.php
- classes/search/ProductsSearchProvider.php
- models/Variant.php
> Search fixes

- classes/index/mysql/MySQL.php
checking if $customIndexData[0] is an array
> Fix for the issue #987

- controllers/Orders.php
> Update Orders.php - removed unnecessary Event firing

- components/productsfilter/scripts.htm
This is a backward compatibility of commit https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/8a3e7319d01fb18a4aba323be10ef9b820dda5de
> Fix typo in productsFilter component

- formwidgets/PropertyFields.php
Fix a partial not found when using a mirrored installation.
> Add backend form widget partials viewpath

- components/product/price.htm
- models/CustomerPaymentMethod.php
- models/Order.php
- updates/version.yaml
Hello @tobias-kuendig,
2 bugfixes: #1145 and #1118 ([see comment](https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/1118#issuecomment-2147648200)).
Since the stripe method is a very important function, I thought it would be good to deliver the patch immediately.
Sincerely,
Sam.
> Minor Bugfixes v3.3.1

- models/PaymentMethod.php
It looks like I finally really need it...
> Made PaymentMethod instructions attribute translatable

- lang/fr/lang.php
Translate cart_limit_reached message
> Update French lang

- classes/payments/PaymentResult.php
This update listens to a `log_failed_payments` flag in `config/features.php` to control whether failed payment attempts should be logged.
If disabled, a failed payment will not be logged in the Event log.
The order’s payment state is still updated to `FailedState` regardless of the config setting.
Default behavior remains unchanged (logging is enabled unless explicitly turned off).
> Make failed payment logging optional via config flag

- classes/jobs/SendOrderConfirmationToCustomer.php
- classes/jobs/SendVirtualProductFiles.php
Add support for RainLab Translate's [Mail Template Translation](https://github.com/rainlab/translate-plugin?tab=readme-ov-file#content--mail-template-translation)
> Set job locale from order lang

- models/GeneralSettings.php
Backport of commit https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/712531ad54359f1e0684c947a5b1cced2d0dc92d to V2 branch
> [FIX] return cms pages with checkout and quickCheckout

- components/Product.php
Same issue as https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/1229
> Filter empty values

- lang/fr/lang.php
Bad translate inverse firstname and lastname
> Update fr lang.php
